[package]
name = "simplicial_topology"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31"
itertools = "0.10.5"
rand = "0.8.5"
num-integer = "0.1.45"
rayon = "1.7.0"
ndarray = "0.15.6"